exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "*.bat", "*.code-workspace"]
destination         : ../houston-youth-computer-science-group.github.io